name: PR comment action

on:
  issue_comment:
    types: [created]

jobs:
  yolo:
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: [ubuntu-latest]
    steps:
      - name: First Step
        if: contains(github.event.comment.body, '/bang')
        run: echo "Action triggered by /bang comment!"
