# name: Comment Workflow

# on:
#   issue_comment:
#     types: [created]

# jobs:
#   generate-preview-url:
#     name: Preview Url
#     if: |
#       github.event.issue.pull_request &&
#       contains(github.event.comment.body, '/generate-preview-url')
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Generate the url and stuff"

#   run-e2e-tests:
#     name: E2E Tests
#     if: |
#       github.event.issue.pull_request &&
#       contains(github.event.comment.body, '/run-e2e-tests')
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "Run the tests and stuff"

name: Comment Workflow

on:
  issue_comment:
    types: [created]

jobs:
  process-comment:
    name: Process PR Comment
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Log Comment Content
        run: |
          echo "Comment content: '${{ github.event.comment.body }}'"

      - name: Check for Commands and Run Actions
        run: |
          COMMENT="${{ github.event.comment.body }}"

          # Split COMMENT into an array of words
          IFS=' ' read -r -a words <<< "$COMMENT"

          # Initialize flags
          generate_preview_url=false
          run_e2e_tests=false

          # Check for exact commands in words array
          for word in "${words[@]}"; do
            if [[ "$word" == "/generate-preview-url" ]]; then
              generate_preview_url=true
            elif [[ "$word" == "/run-e2e-tests" ]]; then
              run_e2e_tests=true
            fi
          done

          # Run actions based on flags
          if [ "$generate_preview_url" = true ]; then
            echo "Command /generate-preview-url found! Generating the preview URL..."
            # Replace this echo with actual URL generation commands
          else
            echo "/generate-preview-url not found in comment."
          fi

          if [ "$run_e2e_tests" = true ]; then
            echo "Command /run-e2e-tests found! Running E2E tests..."
            # Replace this echo with actual E2E test commands
          else
            echo "/run-e2e-tests not found in comment."
          fi
        shell: bash
