name: Run on PR comment

on:
  issue_comment:
    types: [created]

jobs:
  run-on-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add additional steps here
      - name: Run Action
        run: |
          echo "Running action as /bang comment was detected."
